version: "3.7"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - celtra_lotery_network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: beny
    ports:
      - $MYSQL_DOCKER_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  app:
    restart: unless-stopped
    networks:
      - celtra_lotery_network
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    image: scraper
    env_file:
      - ./.env
    ports:
      - $NODEJS_DOCKER_PORT:$NODEJS_DOCKER_PORT
    volumes:
      - ./scraper:/scraper
      - /scraper/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data:

networks:
  celtra_lotery_network:
